### ISSUE TITLE
Need to check for Ifpack2 availability.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17309]
Following #17183, I get this build failure:
```
/home/fac/g/bangerth/p/deal.II/1/dealii/include/deal.II/lac/trilinos_tpetra_types.h:30:14: fatal error: Ifpack2_Preconditioner.hpp: No such file or directory
   30 | #    include <Ifpack2_Preconditioner.hpp>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I'm using Trilinos 15.0, and apparently did not enable Ifpack2. We either need to check whether Ifpack2 is enabled when including (and using) these include files, or we just need to require it when configuring Trilinos+Tpetra in cmake.

@jpthiele FYI.

**Comment by kronbichler** [comment]
I merged this too quickly apparently, our CI is not checking tpetra.

**Comment by jpthiele** [comment]
We have a check but that has a full installation, so we miss the config where Ifpack2 was not installed.

As to Wolfgangs question: 
Currently, for Trilinos we require 
Teuchos and from the Epetra stack Amesos,Epetra,Ifpack,AztecOO and ML
The counterparts are
Amesos2, Tpetra, Ifpack2, Belos and MueLu

Currently, we are still missing Belos and MueLu but my plan is to check tomorrow if MueLu works and add a PR if it does.
Afterwards I will work on the Belos wrappers. 
To make transfer easier, my feeling is that we should start with printing an info or warning message along the lines of
"Tpetra found, but missing the following packages for full functionality.\n${missing}\n In future versions of deal.II these will be a requirement."

Then maybe for 9.6.1 we can make them a hard requirement.
And at some point, once Epetra is removed from Trilinos (16.0 possibly) 
we should switch things around anyways.

**Comment by bangerth** [comment]
I would not mind just requiring the Tpetra-using packages when using Tpetra, in the same way as we require the Epetra-using packages when using Epetra.

**Comment by tamiko** [comment]
Let's address this question in a future pull request. Closing as completed for the release.

**Comment by bangerth** [comment]
@tamiko I don't think we addressed this. Since I ran into a compilation error, I think it would be good if we could find a solution before the release.

**Comment by kronbichler** [comment]
Just to clarify, do you still have the compilation error after #17311? I posted what I believe is a fix there, but I couldn't verify yet, so I'd be curious if there are problems left.

**Comment by bangerth** [comment]
Yes, I can compile. I thought that there was more to it.

(For some reason, I have lost the ability to link anything with deal.II with Tpetra, though, so I can't test things any more. I have a million undefined symbols that are related to Xpetra. When I disable Xpetra in Trilinos, I get other failures. But all of this is unrelated, the Ifpack issue is gone at least.)

**Comment by jpthiele** [comment]
It seems to me that Trilinos is not always able to add its TPLs to the link list for downstream packages. 
I have to add some things to environment variables to be able to run programs with Trilinos.
