### ISSUE TITLE
deal.II/lac/la_vector.h(114): error C2908: explicit specialization; 'dealii::LinearAlgebra::VectorSpaceVector<Number> &dealii::LinearAlgebra::Vector<Number>::operator *=(const Number)' has already been instantiated

### ISSUE THREAD

**Issue by loylick** [dealii/dealii#2875]
One more strange error. It is fixed if I comment out the line 22 in la_vector.cc:  #include "la_vector.inst"
After commenting it the file is compiled perfectly.  I attached my la_vector.inst file in case yours is not the same.
[LaVector_issue.txt](https://github.com/dealii/dealii/files/385243/LaVector_issue.txt)
[la_vector.inst.txt](https://github.com/dealii/dealii/files/385267/la_vector.inst.txt)

**Comment by loylick** [comment]
I commented  #include "la_vector.inst" in la_vector.cc and #include "la_parallel_block_vector.inst" in la_parallel_block_vector.cc after that everything compiled well. Maybe I have not imbibed a great purpose of la_vector.inst and la_parallel_block_vector.inst but it seemed to me that they do just nothing.  How can I run some tests to verify that the library works as it should?

**Comment by bangerth** [comment]
That's not sufficient. The file makes sure we compile the class for the typical template arguments. The `#include` really is necessary. By taking it out, you just remove the code that triggers the compiler error, but not solve the problem.

Your line numbers appear to be off. What version of the repository are you on? For example, I have this code on line *113* of `la_vector.h`:
```
virtual Vector<Number> &operator*= (const Number factor);
```
but your compiler records it as line 114.

**Comment by bangerth** [comment]
Also, I'm curious if you could try the following: the first error in your log appears to be with the function
```
virtual Vector<Number> &operator*= (const Number factor);
```
What happens if you change this to the following:
```
virtual VectorSpaceVector<Number> &operator*= (const Number factor);
```
and then make the same change to the return type in the definition in line 77 of `la_vector.templates.h`? Does the first error in your log disappear? (The ones about the other operators will of course remain.)

**Comment by bangerth** [comment]
By the way, the error is clearly bogus. Error C2908 is explained here https://msdn.microsoft.com/en-us/library/0w9xyawz.aspx but has nothing to do with the current context :-(

**Comment by loylick** [comment]
virtual VectorSpaceVector<Number> &operator*= (const Number factor); this substitute worked, the error about LinearAlgebra::Vector<Number>::operator *=(const Number)  disappeared.

**Comment by loylick** [comment]
I did not understand why the compiler reports:
deal.II/lac/la_vector.h(119): error C2908: explicit specialization; 'dealii::LinearAlgebra::VectorSpaceVector<Number> &dealii::LinearAlgebra::Vector<Number>::operator /=(const Number)' has already been instantiated
whereas I have virtual Vector<Number> &operator/= (const Number factor); at this line
The return type is different compiler gives :VectorSpaceVector<Number> but in the code we have Vector<Number>..

**Comment by tamiko** [comment]
>  it is not how virtual inheritance works the signature and return type must remain the same as they were in the parent class.

This is not correct. The following example is perfectly legal C++ code (remove the ```override``` statement for C++03):
```
class A
{
public:
  virtual A &foo()
  {
    return *this;
  }
};

class B : public A
{
  virtual B &foo() override
  {
    return *this;
  }
};
```
The trick is that the standard allows for "covariant return types": https://en.wikipedia.org/wiki/Covariant_return_type

**Comment by tamiko** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/590625/visual-c-incorrectly-reports-ambiguity-when-covariance-is-used-with-virtual-inheritance

**Comment by tamiko** [comment]
@loylick 
@Rombur @bangerth @davydden @kronbichler @tjhei *ping*

What's very unfortunate about this issue is the fact that we *cannot* change our function signatures for the ```operator``` overrides.

The only solution I see to resolve this issue would be to redesign the ```VectorSpaceVector``` and ```ReadWriteVector``` class hierarchy we just merged to mainline. (Given the fact how much work went into the cleanup and redesign, I'm not exactly eager to even consider this to be an option.)

**Comment by Rombur** [comment]
Damn. Can we get ride of ```VectorSpaceVector``` and just say that all the vectors, which are now derived from it, need to implement the same minimal interface? This would solve the ambiguity problem we have in #2837 at the same time.

**Comment by bangerth** [comment]
@tamiko -- your link only outlines a problem with virtual inheritance, which (I hope) we don't use here.

@loylick -- can you try to compile the following little program that I think should demonstrate the problem?
```
template <typename T>
struct B
{
  virtual B<T> * f() {}
};

template <typename T>
struct D :  B<T>
{
  virtual D<T> * f() {}
};

template struct B<int>;
template struct D<int>;
```
I suspect that will fail.

By way of explanation, in @tamiko's little example, when we declare
```
class B : public A
{
  virtual B &foo() { ...do_something...}    // note: return type is B&, not A&
};
```
what this really does is the following:
```
class B : public A
{
  virtual A &foo() { B &b = ...the other foo() function...;  return (A&)b; };
  virtual B &foo() { ...do_something...}    // note: return type is B&, not A&
};
```
In other words, it creates *two* `foo` functions, one with the old interface (which can not be further overloaded in classes derived from `B` -- in other words, it is `final`) and a second, new virtual function.

My suspicion is that the compiler gets itself confused about this when instantiating the template. In particular, it complains about the *first* of these two functions, with the old return type, even though that never appears in our code.

I'd be very interested in seeing whether the little testcase compiles. If not, it would give us a way to test whether a compiler works or not, and only use workarounds in cases where the compiler is broken.

**Comment by loylick** [comment]
I modified a bit your code by adding return statement:
template <typename T>
struct B
{
  virtual B<T> * f() { return this; }
};

template <typename T>
struct D :  B<T>
{
  virtual D<T> * f() { return this; }
};

template struct B<int>;
template struct D<int>;
In such form it compiled well.

**Comment by bangerth** [comment]
Hm, dang. Do you know how to reduce a testcase to its minimum? In essence, you'd start by throwing out more and more stuff from the `la_vector.template.h` to make the file shorter and shorter but so that the compiler error still remains. When it's small enough, you just put its entire content into the .cc file. Then you do the same with `la_vector.h`. Etc. Ultimately, you'd end up with a small and *self contained* file that does not compile. We could use this during `cmake` time to figure out whether the compiler has a bug or not. Want to give this a try?

**Comment by loylick** [comment]
The last example was with virtual inheritance which you do not use. So maybe the reason of the error is not in the inheritance. Ok. I'll try to reduce the case.

**Comment by tamiko** [comment]
@bangerth 
> your link only outlines a problem with virtual inheritance, which (I hope) we don't use here.

My bet is that the issue is not due to the virtual inheritance but due to multiple inheritance in combination with covariant return types---at least this is what all examples have in common:

```
struct D : B, C { ... }
```

```
class Vector : public ReadWriteVector<Number>, public VectorSpaceVector<Number> { ... }
```

**Comment by bangerth** [comment]
Fair point. If you could come up with a small example, that would be excellent!

**Comment by tamiko** [comment]
@loylick @bangerth 
What about this?
```
class A
{
public:
  virtual A &foo()
  {
    return *this;
  }
};

class C { } ;

class B : public A, public C
{
  virtual B &foo() override
  {
    return *this;
  }
};
```

**Comment by agrayver** [comment]
I've got an access to a Windows 64 machine with VS2013 Ultimate Ed Update 5 (latest), therefore can contribute a bit. 

@tamiko your example compiles find both as a sepearate project or part of la_vector.h file.

**Comment by loylick** [comment]
Finally I did reduced the case. it is something for what I can not figure out the reason.
template \<typename Number\>
  class VectorSpaceVector
  {
  public:
    virtual VectorSpaceVector\<Number\> &operator*= (const Number factor) = 0;
  };

class Subscriptor
{
public:
   virtual ~Subscriptor();
};

template \<typename Number\>
  class ReadWriteVector : public Subscriptor {};

 template \<typename Number\>
  class Vector : public ReadWriteVector\<Number\>, public VectorSpaceVector\<Number\>
  {
  public:
       
    virtual Vector\<Number\> &operator*= (const Number factor);
 
  };

  template \<typename Number\>
  Vector<Number> &Vector<Number>::operator*= (const Number factor)
  {
      return *this;
  }

  template class Vector\< double \>;

**Comment by loylick** [comment]
I think I 'll post it to stackoverflow, they like such quizzes.

**Comment by bangerth** [comment]
Great small testcase! Can you post the error message you get for it?

**Comment by loylick** [comment]
the same message: error C2908: explicit specialization;
 'VectorSpaceVector\<Number\> &Vector\<Number\>::operator *=(const Number)' has already been instantiated
1>          with
1>          [
1>              Number=double
1>          ]

**Comment by tjhei** [comment]
I would like to move forward with this issue so that we can compile with MSVC again (to be able to do the 8.5 release). Some suggestions:
1. do not instantiate LA::Vector on windows (not very useful right now anyways and we don't support MPI on windows).
2. Get rid of the covariant return type for these operators and just return void (only on MSVC?)?
3. Rethink the design: in parallel we won't have a vector that does both, ReadWrite and VectorSpace, so do we really need that design in serial? Maybe it is okay to always ask the user to work with two different vector types.
4. VectorSpaceVector is just an interface class, but is it really necessary? We can always use template classes instead of inheritance. The places where this is used are mostly linear solvers, right? Those are templated already.

**Comment by bangerth** [comment]
I would suggest just `#include`ing the `.templates.h` at the bottom of the header file for MSVC, and not including the `.inst.in` file in the source file. This seems like the least disruptive approach.

**Comment by loylick** [comment]
tjhei said: "we don't support MPI on windows". Can you explain to me guys what it implies? Does it mean that PETS and SLEPC compiled with MPI support will not work with dealii under Windows?

**Comment by tjhei** [comment]
Windows support is still very experimental and I don't know of anyone who has used any external packages or MPI so far. I would be surprised if it works. We are not even able to run the whole testsuite at the moment. Also see https://github.com/dealii/dealii/issues/1921

**Comment by loylick** [comment]
Could you tell me what functionality affects this bug fix with not including the .inst.in file in the source?

**Comment by Rombur** [comment]
Nothing. If you include the ```.templates.h```, the class will be generated when you call the function in your code instead of when deal.II is compiled.
